name: Lint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.4.1
        uses: actions/setup-node@v4
        with:
          node-version: 22.4.1
      - run: npm ci
      - name: Lint
        run: npm run lint